"""create_initial_catalog_schema

Revision ID: a39171b7ca9b
Revises: 
Create Date: 2026-09-26 01:15:07.271395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39171b7ca9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_generation_number')
    )
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generations_number'), ['number'], unique=True)

    op.create_table('pokemon',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('species_name', sa.String(length=64), nullable=False),
    sa.Column('form_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species_name', 'form_name', name='uq_pokemon_species_form')
    )
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pokemon_dex_number'), ['dex_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_pokemon_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pokemon_species_name'), ['species_name'], unique=False)

    op.create_table('types',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('generation_id', sa.String(length=32), nullable=False),
    sa.Column('version_group', sa.String(length=64), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_generation_id'), ['generation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_version_group'), ['version_group'], unique=False)

    op.create_table('type_chart_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chart_version', sa.String(length=32), nullable=False),
    sa.Column('attacker_type_id', sa.String(length=32), nullable=False),
    sa.Column('defender_type_id', sa.String(length=32), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attacker_type_id'], ['types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defender_type_id'], ['types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chart_version', 'attacker_type_id', 'defender_type_id', name='uq_type_chart_entry')
    )
    with op.batch_alter_table('type_chart_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_type_chart_entries_attacker_type_id'), ['attacker_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_type_chart_entries_chart_version'), ['chart_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_type_chart_entries_defender_type_id'), ['defender_type_id'], unique=False)

    op.create_table('base_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_id', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('atk', sa.Integer(), nullable=False),
    sa.Column('def', sa.Integer(), nullable=False),
    sa.Column('spa', sa.Integer(), nullable=False),
    sa.Column('spd', sa.Integer(), nullable=False),
    sa.Column('spe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pokemon_id', 'game_id', name='uq_pokemon_base_stats')
    )
    with op.batch_alter_table('base_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_base_stats_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_stats_pokemon_id'), ['pokemon_id'], unique=False)

    op.create_table('game_pokemon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('pokemon_id', sa.String(length=64), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'pokemon_id', name='uq_game_pokemon')
    )
    with op.batch_alter_table('game_pokemon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_pokemon_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_pokemon_pokemon_id'), ['pokemon_id'], unique=False)

    op.create_table('game_rule_profiles',
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('type_chart_version', sa.String(length=32), nullable=False),
    sa.Column('has_fairy_type', sa.Boolean(), nullable=False),
    sa.Column('steel_resists_dark_ghost', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('pokemon_abilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_id', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('ability_id', sa.String(length=64), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pokemon_id', 'game_id', 'ability_id', name='uq_pokemon_ability')
    )
    with op.batch_alter_table('pokemon_abilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pokemon_abilities_ability_id'), ['ability_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pokemon_abilities_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pokemon_abilities_pokemon_id'), ['pokemon_id'], unique=False)

    op.create_table('pokemon_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_id', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.String(length=32), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pokemon_id', 'game_id', 'slot', name='uq_pokemon_type_slot')
    )
    with op.batch_alter_table('pokemon_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pokemon_types_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pokemon_types_pokemon_id'), ['pokemon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pokemon_types_type_id'), ['type_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pokemon_types_type_id'))
        batch_op.drop_index(batch_op.f('ix_pokemon_types_pokemon_id'))
        batch_op.drop_index(batch_op.f('ix_pokemon_types_game_id'))

    op.drop_table('pokemon_types')
    with op.batch_alter_table('pokemon_abilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pokemon_abilities_pokemon_id'))
        batch_op.drop_index(batch_op.f('ix_pokemon_abilities_game_id'))
        batch_op.drop_index(batch_op.f('ix_pokemon_abilities_ability_id'))

    op.drop_table('pokemon_abilities')
    op.drop_table('game_rule_profiles')
    with op.batch_alter_table('game_pokemon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_pokemon_pokemon_id'))
        batch_op.drop_index(batch_op.f('ix_game_pokemon_game_id'))

    op.drop_table('game_pokemon')
    with op.batch_alter_table('base_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_base_stats_pokemon_id'))
        batch_op.drop_index(batch_op.f('ix_base_stats_game_id'))

    op.drop_table('base_stats')
    with op.batch_alter_table('type_chart_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_type_chart_entries_defender_type_id'))
        batch_op.drop_index(batch_op.f('ix_type_chart_entries_chart_version'))
        batch_op.drop_index(batch_op.f('ix_type_chart_entries_attacker_type_id'))

    op.drop_table('type_chart_entries')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_version_group'))
        batch_op.drop_index(batch_op.f('ix_games_generation_id'))

    op.drop_table('games')
    op.drop_table('types')
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pokemon_species_name'))
        batch_op.drop_index(batch_op.f('ix_pokemon_name'))
        batch_op.drop_index(batch_op.f('ix_pokemon_dex_number'))

    op.drop_table('pokemon')
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generations_number'))

    op.drop_table('generations')
    op.drop_table('abilities')
    # ### end Alembic commands ###
